version: '3.7'

services:
  db:
    container_name: pg_container
    env_file:
      - .env
    image: postgres:11.5-alpine
    restart: always
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    ports:
      - 25432:5432
  
  node:
    container_name: node_container
    build: .
    links:
      - db
    depends_on:
      - db
    command: npm run startdb
    environment:
      WAIT_HOSTS: db:5432